require:
  - rubocop-performance
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  DisplayStyleGuide: true
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/**/*'
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace
Metrics/BlockLength:
  Exclude:
    - 'spec/**/**/*'
    - '*.gemspec'
Metrics/LineLength:
  Max: 100
Metrics/ModuleLength:
  Enabled: false
Naming/FileName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Style/AccessModifierDeclarations:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
